<!DOCTYPE html>
<html>
<head>
    <title>Automated Database Backup</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
    <h2>Database Backup</h2>
    <p>Please find attached the automated database backup for {{ date('Y-m-d') }}.</p>
    
    <p>This backup contains a complete dump of the POS system database. Keep this file safe for disaster recovery.</p>
    
    <p style="margin-top: 30px; font-size: 12px; color: #7f8c8d;">
        This is an automated message generated by the Avexia POS System.
    </p>
</body>
</html>
